### ISSUE TITLE
Automagickally publish to .NuGet

### ISSUE THREAD

**Issue by nitzel** [jekstrom/SmallOauth1#3]
- [x] Make sure the code on GitHub is the same (or better) than on NuGet
- [x] Automated publishing would help with collaboration as you don't have to do it each time in addition to accepting a merge. This didn't look too hard: https://weblogs.asp.net/bsimser/automatically-publishing-nuget-packages-from-github

**Comment by jekstrom** [comment]
Yeah I should be able to set that up. Thanks for the suggestion.

Sorry I have the wrong version up on NuGet currently. I'll get that fixed later today.

**Comment by jekstrom** [comment]
Updated version pushed as 1.0.1.

Tested working with MyGet by 1.0.3 (no functionality changed, though).

I didn't set it to automatically push to NuGet on each update, since that might get a little noisy. I don't expect a ton of changes to this library anyway, though.

Each update from this github repo will get pushed to https://www.myget.org/F/smalloauth1/ and I should get a notification from MyGet so I can go and push the release version to NuGet when it is merged.
